# A single state bit constant from RobotState.msg
cpr_common_msgs/RobotState single_state

uint8 ACTION_CLEAR = 0
uint8 ACTION_ASSERT = 1
uint8 action

duration timeout

string source
---
uint8 STATUS_SUCCESS = 0
uint8 STATUS_INVALID_SINGLE_STATE = 1
uint8 STATUS_INVALID_ACTION = 2
uint8 STATUS_EMPTY_SOURCE = 3
uint8 status

string status_message
